/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Thu Nov 19 18:57:37 2020
#  Design:            hlth_chain
#  Command:           write_netlist hlth_L_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Nov 19 2020 18:56:27 CET (Nov 19 2020 17:56:27 UTC)
// Verification Directory fv/hlth_chain 
module hlth_chain (
	I, 
	Z);
   input I;
   output Z;

   // Internal wires
   wire [10:0] B;

   INV_X12 IX12 (.I(B[6]),
	.ZN(B[7]));

   // Not fitted
   // INV_X12 \genblk1[0].IX12  (.I(I),
	// .ZN(B[1]));

   // Changed
   // INV_X16 \genblk1[0].IX16  (.I(B[1]),
	// .ZN(B[2]));   
   INV_X16 \genblk1[0].IX16  (.I(I),
	.ZN(B[2]));

   INV_X12 \genblk1[2].IX12  (.I(B[2]),
	.ZN(B[3]));
   INV_X16 \genblk1[2].IX16  (.I(B[3]),
	.ZN(B[4]));
   INV_X12 \genblk1[4].IX12  (.I(B[4]),
	.ZN(B[5]));
   INV_X16 \genblk1[4].IX16  (.I(B[5]),
	.ZN(B[6]));
   INV_X8 \genblk2[7].IX8  (.I(B[7]),
	.ZN(B[8]));

   // Changed
   // INV_X8 \genblk2[8].IX8  (.I(B[8]),
	// .ZN(B[9]));
   INV_X8 \genblk2[8].IX8  (.I(B[8]),
	.ZN(Z));

   // Not fitted
   // INV_X8 \genblk2[9].IX8  (.I(B[9]),
	// .ZN(Z));
endmodule

