/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Wed Mar 10 15:15:05 2021
#  Design:            nor_gate
#  Command:           write_netlist nor_gate_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Mar 10 2021 15:14:20 CET (Mar 10 2021 14:14:20 UTC)
// Verification Directory fv/nor_gate 
module nor_gate (
	A1, 
	A2, 
	Z);
   input A1;
   input A2;
   output Z;

   NOR2_X2_NOR1 NOR1 (.A1(A1),
	.A2(A2),
	.ZN(Z));
endmodule
