/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Fri Apr 16 09:24:46 2021
#  Design:            nor_buf
#  Command:           write_netlist nor_buf_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Apr 16 2021 09:23:57 CEST (Apr 16 2021 07:23:57 UTC)
// Verification Directory fv/nor_buf 
module nor_buf (
	A1, 
	A2, 
	Z);
   input A1;
   input A2;
   output Z;

   // Internal wires
   wire A1_wire_2;
   wire A2_wire_2;
   wire Z_wire;

   BUF_X4 BUF_A1_1 (.I(A1),
	.Z(A1_wire_2));
   BUF_X4 BUF_A2_1 (.I(A2),
	.Z(A2_wire_2));
   BUF_X4 BUF_Z_1 (.I(Z_wire),
	.Z(Z));
   NOR2_X2 NOR1 (.A1(A1_wire_2),
	.A2(A2_wire_2),
	.ZN(Z_wire));
endmodule

