/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Fri May 28 07:51:27 2021
#  Design:            nor_bufs2
#  Command:           write_netlist nor_bufs2_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: May 28 2021 07:50:27 CEST (May 28 2021 05:50:27 UTC)
// Verification Directory fv/nor_bufs2 
module nor_bufs2 (
	A1, 
	A2, 
	Z);
   input A1;
   input A2;
   output Z;

   // Internal wires
   wire A1_wire_2;
   wire A1_wire_3;
   wire A1_wire_4;
   wire A1_wire_5;
   wire A1_wire_6;
   wire A2_wire_2;
   wire A2_wire_3;
   wire A2_wire_4;
   wire A2_wire_5;
   wire A2_wire_6;
   wire Z_wire_1;
   wire Z_wire_3;
   wire Z_wire_4;
   wire Z_wire_5;
   wire Z_wire_6;

   
   assign A1_wire_6 = A1;
   assign A2_wire_6 = A2;
   assign Z = Z_wire_1;

   // BUF_X2_BUFA11 BUF_A1_1 (.I(A1),
	// .Z(A1_wire_2));
   // BUF_X2_BUFA12 BUF_A1_2 (.I(A1_wire_2),
	// .Z(A1_wire_3));
   // BUF_X2_BUFA13 BUF_A1_3 (.I(A1_wire_3),
	// .Z(A1_wire_4));
   // BUF_X2_BUFA14 BUF_A1_4 (.I(A1_wire_4),
	// .Z(A1_wire_5));
   // BUF_X2_BUFA15 BUF_A1_5 (.I(A1_wire_5),
	// .Z(A1_wire_6));
   // BUF_X2_BUFA21 BUF_A2_1 (.I(A2),
	// .Z(A2_wire_2));
   // BUF_X2_BUFA22 BUF_A2_2 (.I(A2_wire_2),
	// .Z(A2_wire_3));
   // BUF_X2_BUFA23 BUF_A2_3 (.I(A2_wire_3),
	// .Z(A2_wire_4));
   // BUF_X2_BUFA24 BUF_A2_4 (.I(A2_wire_4),
	// .Z(A2_wire_5));
   // BUF_X2_BUFA25 BUF_A2_5 (.I(A2_wire_5),
	// .Z(A2_wire_6));
   // BUF_X2_BUFZ1 BUF_Z_1 (.I(1'b0),
	// .Z(Z));
   // BUF_X2_BUFZ2 BUF_Z_2 (.I(Z),
	// .Z(Z_wire_3));
   // BUF_X2_BUFZ3 BUF_Z_3 (.I(Z_wire_3),
	// .Z(Z_wire_4));
   // BUF_X2_BUFZ4 BUF_Z_4 (.I(Z_wire_4),
	// .Z(Z_wire_5));
   // BUF_X2_BUFZ5 BUF_Z_5 (.I(Z_wire_5),
	// .Z(Z_wire_6));

   NOR2_X2_NOR1 NOR1 (.A1(A1_wire_6),
	.A2(A2_wire_6),
	.ZN(Z_wire_1));
endmodule
