/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Sun May 23 09:10:18 2021
#  Design:            nor_bufs
#  Command:           write_netlist nor_bufs_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: May 23 2021 09:09:18 CEST (May 23 2021 07:09:18 UTC)
// Verification Directory fv/nor_bufs 
module nor_bufs (
	A1_wire, 
	A2_wire, 
	Z_wire);
   input A1_wire;
   input A2_wire;
   output Z_wire;

   // Internal wires
   // wire A1_wire_2;
   // wire A1_wire_3;
   // wire A1_wire_4;
   // wire A1_wire_5;
   // wire A1_wire_6;
   // wire A2_wire_2;
   // wire A2_wire_3;
   // wire A2_wire_4;
   // wire A2_wire_5;
   // wire A2_wire_6;
   // wire Z_wire_1;

   // BUF_X2_BUFA11 BUF_A1_1 (.I(A1),
	// .Z(A1_wire_2));
   // BUF_X2_BUFA12 BUF_A1_2 (.I(A1_wire_2),
	// .Z(A1_wire_3));
   // BUF_X2_BUFA13 BUF_A1_3 (.I(A1_wire_3),
	// .Z(A1_wire_4));
   // BUF_X2_BUFA14 BUF_A1_4 (.I(A1_wire_4),
	// .Z(A1_wire_5));
   // BUF_X2_BUFA15 BUF_A1_5 (.I(A1_wire_5),
	// .Z(A1_wire_6));
   // BUF_X2_BUFA21 BUF_A2_1 (.I(A2),
	// .Z(A2_wire_2));
   // BUF_X2_BUFA22 BUF_A2_2 (.I(A2_wire_2),
	// .Z(A2_wire_3));
   // BUF_X2_BUFA23 BUF_A2_3 (.I(A2_wire_3),
	// .Z(A2_wire_4));
   // BUF_X2_BUFA24 BUF_A2_4 (.I(A2_wire_4),
	// .Z(A2_wire_5));
   // BUF_X2_BUFA25 BUF_A2_5 (.I(A2_wire_5),
	// .Z(A2_wire_6));
   // BUF_X2_BUFZ1 BUF_Z_1 (.I(Z_wire_1),
	// .Z(Z));
   // NOR2_X2_NOR1 NOR1 (.A1(A1_wire_6),
	// .A2(A2_wire_6),
	// .ZN(Z_wire_1));

   NOR2_X2_NOR1 NOR1 (.A1(A1_wire),
	.A2(A2_wire),
	.ZN(Z_wire));
endmodule
