/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Fri Nov 13 10:56:08 2020
#  Design:            buf_x4_chain
#  Command:           write_netlist buf_x4_chain_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Nov 13 2020 10:55:07 CET (Nov 13 2020 09:55:07 UTC)
// Verification Directory fv/buf_x4_chain 
module buf_x4_chain (
	I, 
	Z);
   input I;
   output Z;

   // Internal wires
   wire [10:0] B;

   BUF_X4_genblk10BX4 \genblk1[0].BX4  (.I(I),
	.Z(B[1]));
   BUF_X4_genblk11BX4 \genblk1[1].BX4  (.I(B[1]),
	.Z(B[2]));
   BUF_X4_genblk12BX4 \genblk1[2].BX4  (.I(B[2]),
	.Z(B[3]));
   BUF_X4_genblk13BX4 \genblk1[3].BX4  (.I(B[3]),
	.Z(B[4]));
   BUF_X4_genblk14BX4 \genblk1[4].BX4  (.I(B[4]),
	.Z(B[5]));
   BUF_X4_genblk15BX4 \genblk1[5].BX4  (.I(B[5]),
	.Z(B[6]));
   BUF_X4_genblk16BX4 \genblk1[6].BX4  (.I(B[6]),
	.Z(B[7]));
   BUF_X4_genblk17BX4 \genblk1[7].BX4  (.I(B[7]),
	.Z(B[8]));
   BUF_X4_genblk18BX4 \genblk1[8].BX4  (.I(B[8]),
	.Z(B[9]));
   BUF_X4_genblk19BX4 \genblk1[9].BX4  (.I(B[9]),
	.Z(Z));
endmodule
