/*
###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID asic.ecs.tuwien.ac.at)
#  Generated on:      Mon Nov 23 08:05:25 2020
#  Design:            inv_x2_chain
#  Command:           write_netlist inv_x2_chain_post.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Nov 23 2020 08:04:35 CET (Nov 23 2020 07:04:35 UTC)
// Verification Directory fv/inv_x8_chain 
module inv_x2_chain (
	I, 
	Z);
   input I;
   output Z;

   // Internal wires
   wire [10:0] B;

   // INV_X2 \genblk1[0].IX2  (.I(I),
	// .ZN(B[1]));
   INV_X2 \genblk1[1].IX2  (.I(I),
	.ZN(B[2]));
   INV_X2 \genblk1[2].IX2  (.I(B[2]),
	.ZN(B[3]));
   INV_X2 \genblk1[3].IX2  (.I(B[3]),
	.ZN(B[4]));
   INV_X2 \genblk1[4].IX2  (.I(B[4]),
	.ZN(B[5]));
   INV_X2 \genblk1[5].IX2  (.I(B[5]),
	.ZN(B[6]));
   INV_X2 \genblk1[6].IX2  (.I(B[6]),
	.ZN(B[7]));
   INV_X2 \genblk1[7].IX2  (.I(B[7]),
	.ZN(B[8]));
   INV_X2 \genblk1[8].IX2  (.I(B[8]),
	.ZN(Z));
   // INV_X2 \genblk1[9].IX2  (.I(B[9]),
	// .ZN(Z));
endmodule

